name: NoikzFly
version: '1.2.1'
main: me.noikz.noikzfly.Main
api-version: 1.20
authors: [ Noikz ]
commands:
  fly:
    description: Makes you fly!
    usage: /<command>
    aliases: []
  noikzfly:
    description: The main command of NoikzFly.
    usage: /<command>
    aliases: []
  flyspeed:
    description: Changes your flight speed.
    usage: /<command>
    aliases: []