name: NoikzFly
version: 1.0.0
main: me.noikzgaming.noikzfly.Main
api-version: 1.17

commands:
  fly:
    description: Makes you fly!
    usage: /<command>
    aliases: []
  noikzfly:
    description: The main command of NoikzFly.
    usage: /<command>
    aliases: []